L01/Models/ErrorViewModel.cs
using System;

namespace L01.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

L01/Models/L01Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace L01.Models
{
    public class L01Context : DbContext
    {
        public L01Context() { }
        public L01Context(DbContextOptions<L01Context> options) : base(options){}
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=KH-CHEN\\MSSQLSERVER2016;Database=l01;Trusted_Connection=True;");
            base.OnConfiguring(optionsBuilder);
        }
        public DbSet<CustomerType> CustomerTypes { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<LoanType> LoanTypes { get; set; }
        public DbSet<Loan> Loans { get; set; }
    }
}

L01/Models/L01Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace L01.Models
{
    public class BaseModel
    {
        public int Id { get; set; }
        public DateTime Created_date { get; set; } = DateTime.Now;
        public DateTime Updated_date { get; set; } = DateTime.Now;
        public bool Active { get; set; } = true;
    }

    public class Customer : BaseModel
    {
        public int CustomerTypeid { get; set; } 
        public string Name { get; set; }
        public string Code { get; set; }
        public string Sex { get; set; }
        public DateTime dob { get; set; }
        public string IdCard { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Attachment { get; set; }
        public string images { get; set; }
    }
    public class CustomerType : BaseModel
    {
        public string Name { get; set; }
        public int ParentId { get; set; }
    }

    public class LoanType : BaseModel
    {
        public string Name { get; set; }
        public decimal Rate { get; set; }
        public string RateType { get; set; }
        public int Calculation { get; set; }
        public int Period { get; set; }
        public string PeriodType { get; set; }
        public int Payback { get; set; }
        public string PaybackType { get; set; }
        public int RepayAfter { get; set; }
    }

    public class Loan : BaseModel
    {
        public int CustomerId { get; set; }
        public int ContractId { get; set; }
        public int LoanTypeId { get; set; }
        public decimal Amount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal Balance { get; set; }
        public int CurrencyId { get; set; }
        public int Period { get; set; }
        public string PeriodType { get; set; }
        public decimal Rate { get; set; }
        public string RateType { get; set; }
        public DateTime LoanDate { get; set; }
        public DateTime ScheduleStartDate { get; set; }
        public string Status { get; set; }
    }
}

L01/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using L01.Models;
using Microsoft.AspNetCore.Mvc;
using L01.Logic;
namespace L01.Controllers
{
    public class CustomerController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;
            return View(await PaginatedList<Customer>.Paginated(CustomerLogic.Instance.All(),page ?? 1, pageSize));
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var customerType = await CustomerTypeLogic.Instance.Bind();
            ViewBag.customer = customerType;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult<Customer>> Add(Customer customer)
        {
            await CustomerLogic.Instance.Add(customer);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var q = await CustomerLogic.Instance.Find(id);
            var customerType = await CustomerTypeLogic.Instance.Bind();
            ViewBag.customer = customerType;
            return View(q);
        }
        [HttpPost]
        public async Task<ActionResult<Customer>> Edit(Customer customer)
        {
            await CustomerLogic.Instance.Edit(customer);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            return View(await CustomerLogic.Instance.Find(id));
        }
        public async Task<ActionResult> Delete(int id)
        {
            await CustomerLogic.Instance.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

L01/Controllers/CustomerTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using L01.Models;
using L01.Logic;
using Microsoft.EntityFrameworkCore;
namespace L01.Controllers
{
    public class CustomerTypeController : Controller
    {
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 25;
            return View(await PaginatedList<CustomerType>.Paginated(CustomerTypeLogic.Instance.All(), page ?? 1 , pageSize));
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var customerType = await CustomerTypeLogic.Instance.Bind();
            ViewBag.item = customerType;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult<CustomerType>> Add(CustomerType customerType)
        {
            await CustomerTypeLogic.Instance.Add(customerType);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            // bing data to Select tags
            var customerType = await CustomerTypeLogic.Instance.Bind();
            ViewBag.item = customerType;
            var q = await CustomerTypeLogic.Instance.Find(id);
            return View(q); 
        }
        [HttpPost]
        public async Task<ActionResult<CustomerType>> Edit(CustomerType customerType)
        {
            await CustomerTypeLogic.Instance.Edit(customerType);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<ActionResult<CustomerType>> Remove(int id)
        {
            var q = await CustomerTypeLogic.Instance.Find(id);
            return View(q);
        }
        public async Task<ActionResult<CustomerType>> Delete(int id)
        {
            await CustomerTypeLogic.Instance.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

L01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using L01.Models;

namespace L01.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

L01/Views/Customer/Edit.cshtml
@model L01.Models.Customer;
@{
    ViewData["Title"] = "Edit Customer";
}
@section Breadcrumb{
    <ul class="navbar-nav breadcrumb-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home / Customer / Edit / @Model.Id</a>
        </li>
    </ul>
}
<form asp-controller="Customer" asp-action="Edit" method="post">
    <div class="row" style="padding-bottom:105px !important;">
        <div class="col-md-4">
            <div class="col">
                <h4>Customer Information</h4>
                <p>Plase, Fill Customer Information.</p>
            </div>
        </div><!--col-md-4-->
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-body">
                    <div class="row">
                        <input type="hidden" id="id" asp-for="Id" />
                        <div class="col-sm-6">
                            <div form-group>
                                <label for="code" style="font-weight:normal;">Code</label>
                                <input asp-for="Code" class="form-control" type="text" id="code" />
                                <span asp-validation-for="Code" class="text-danger"></span>
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="name" style="font-weight:normal;">Name</label>
                                <input asp-for="Name" type="text" class="form-control" id="name" />
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="dob" style="font-weight:normal;">Date of Birth</label>
                                <div class="input-group">
                                    <input asp-for="dob" type="text" class="form-control float-right" id="dob" autocomplete="off" value="@string.Format("{0:yyyy-MM-dd}", Model.dob)">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fa fa-calendar"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="Sex" style="font-weight:normal;">Gender</label>
                                <select class="form-control" style="width: 100%;" asp-for="Sex" id="sex">
                                    <option>Male</option>
                                    <option>Female</option>
                                </select>
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="customer_type" style="font-weight:normal;">Customer Type</label>
                                <select class="form-control select2" style="width: 100%;" id="customerType" asp-for="CustomerTypeid" asp-items="@(new SelectList(ViewBag.customer,"Id","Name"))">
                                    <option></option>
                                </select>
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="identity_card_no" style="font-weight:normal;">Identity Card No</label>
                                <input asp-for="IdCard" type="text" class="form-control" id="identity_card_no" />
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="phone" style="font-weight:normal;">Phone</label>
                                <input asp-for="Phone" type="text" class="form-control" id="phone" data-inputmask='"mask": "(999) 999-9999"' placeholder="(999) 999-9999" data-mask>
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="email" style="font-weight:normal;">Email</label>
                                <input asp-for="Email" type="text" class="form-control" id="email" />
                            </div>
                        </div><!--col-sm-6-->
                        <div class="col">
                            <div class="form-group">
                                <label for="address" style="font-weight:normal;">Address</label>
                                <textarea class="form-control" id="address" rows="3" asp-for="Address"></textarea>
                            </div>
                        </div><!--col text area-->
                    </div>
                </div><!--card-body-->
            </div><!--card card-default-->
        </div><!--col-md-8-->
        <div class="col-md-4">
            <div class="col">
                <h4>Photo</h4>
                <p>Upload Photo of Customer.</p>
            </div>
        </div><!--col-md-4-->
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <input type="file" name="photp" class="file" hidden asp-for="images" />
                                <div class="col" style="margin-bottom: 10px !important;">
                                    <button type="button" class="browse btn btn-outline-primary">Browse</button>
                                </div>
                                <div class="col-sm-3">
                                    <img src="~/images/default-thumbnail.jpg" alt="..." width="130" height="130" class="img-thumbnail" id="preview">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--card card-default of photo-->
        </div><!--close col-md-8 of photo-->
    </div><!--/ row -->
    <div class="submib-fixed" style="position: fixed; bottom: 0%; left: 0%; background-color: #fbfbfb; width: 100%; padding: 8px;border-top:1px solid #ebe8e8;">
        <a class="btn btn-outline-danger pull-right btn-sm" asp-area="" asp-controller="Customer" asp-action="Index">Cancel</a>
        <button type="submit" class="btn btn-outline-primary btn-sm pull-right" style="margin-right: 10px;padding: 4px 12px 5px 12px;">Save</button>
    </div>
</form>
@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#dob').datepicker({
                todayBtn: "linked",
                'format': 'yyyy-mm-dd',
                'autoclose': true
            });
            $('.select2').select2({
                placeholder: 'Customer Type',
                allowClear: true,
                disabled: false,
            });
            $('[data-mask]').inputmask();
        });
        $(document).on("click", ".browse", function () {
            var file = $(this)
                .parent()
                .parent()
                .parent()
                .find(".file");
            file.trigger("click");
        });
        $('input[type="file"]').change(function (e) {
            var fileName = e.target.files[0].name;
            $("#file").val(fileName);

            var reader = new FileReader();
            reader.onload = function (e) {
                // get loaded data and render thumbnail.
                document.getElementById("preview").src = e.target.result;
            };
            // read the image file as a data URL.
            reader.readAsDataURL(this.files[0]);
        });
    </script>
}

L01/Views/Customer/Remove.cshtml
@model L01.Models.Customer;
@{
    ViewData["Title"] = "Customer";
}
@section Breadcrumb{
    <ul class="navbar-nav breadcrumb-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home / Customer / Remove / @Model.Id</a>
        </li>
    </ul>
}
<form asp-controller="Customer" asp-action="Remove" method="post">
    <div class="row">
        <div class="col-md-4">
            <div class="col">
                <h4>Remove Customer Type</h4>
                <p>Remove Customer Type from Database.</p>
            </div>
        </div><!--End col-md-4-->
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <h5>Are You Sure Want to Delete ?</h5>
                            <i class="fa fa-exclamation-triangle" aria-hidden="true" style="color: #FF9800;font-size: 22px;padding-right: 10px;display:inline-block;"></i>
                            <p style="display:inline-block;">This Will Delete Customer Type <span style="font-weight:bold;">"@Model.Code-@Model.Name"</span> From You Database.</p>
                        </div>
                        <div class="col-sm-12">
                            <a class="btn btn-outline-danger pull-right btn-sm" asp-area="" asp-controller="Customer" asp-action="Index">Cancel</a>
                            <a asp-area="" asp-controller="Customer" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-primary pull-right btn-sm" style="margin-right:10px;">Remove</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

L01/Views/CustomerType/Add.cshtml
@model L01.Models.CustomerType;
@{
    ViewData["Title"] = "Customer Type Add";
}
@section Breadcrumb{
    <ul class="navbar-nav breadcrumb-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home / CustomerType / Add</a>
        </li>
    </ul>
}
    <form asp-controller="CustomerType" asp-action="Add" method="post">
        <div class="row" style="margin-bottom:105px !important;">
            <div class="col-sm-4">
                <div class="col">
                    <h4>Customer Type.</h4>
                    <p>Please, Fill Customer Type Information.</p>
                </div>
            </div><!--end col-sm-4-->
            <div class="col-sm-8">
                <div class="card card-default">
                    <div class="card-body">
                        <div class="row">
                            <input type="hidden" name="id" id="id" asp-for="Id" />
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="name" style="font-weight:normal;">Name</label>
                                    <input type="text" name="name" id="name" asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger">Field Name is Required.</span>
                                </div>
                            </div><!--col-sm-6-->
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="name" style="font-weight:normal;">Customer Type</label>
                                    <select class="form-control" style="width:100%;" asp-for="ParentId" asp-items="@(new SelectList(ViewBag.item,"Id","Name"))">
                                        <option>None</option>
                                    </select>
                                </div>
                            </div><!--col-sm-6-->
                        </div>
                    </div><!--card-body-->
                </div><!--end Card-default of main-->
            </div><!--end col-sm-8-->
        </div><!--end row of main fomr-->
        <div class="submib-fixed" style="position: fixed; bottom: 0%; left: 0%; background-color: #fbfbfb; width: 100%; padding: 8px; border-top:1px solid #ebe8e8;">
            <a class="btn btn-outline-danger pull-right btn-sm" asp-area="" asp-controller="CustomerType" asp-action="Index">Cancel</a>
            <button type="submit" class="btn btn-outline-primary btn-sm pull-right" style="margin-right: 10px;padding: 4px 12px 5px 12px;" id="submit">Save</button>
        </div>
    </form>
@section Scripts{ 
    <script type="text/javascript">
        $(document).ready(function () {
            $('.text-danger').hide();
            $("#submit").on("click", function(e){
                var name = $("#name").val();
                var a = "";
                if (name == "" || name == undefined) {
                    $('.text-danger').show();
                    return false;
                }
            });   
        });
    </script>
}

L01/Views/CustomerType/Remove.cshtml
@model L01.Models.CustomerType;
@{
    ViewData["Title"] = "CustomerType";
}
@section Breadcrumb{
    <ul class="navbar-nav breadcrumb-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home / CustomerType / Remove / @Model.Id</a>
        </li>
    </ul>
}
<form asp-controller="CustomerType" asp-action="Remove" method="post">
    <div class="row">
        <div class="col-md-4">
            <div class="col">
                <h4>Remove Customer Type</h4>
                <p>Remove Customer Type from Database.</p>
            </div>
        </div><!--End col-md-4-->
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <h5>Are You Sure Want to Delete ?</h5>
                            <i class="fa fa-exclamation-triangle" aria-hidden="true" style="color: #FF9800;font-size: 22px;padding-right: 10px;display:inline-block;"></i>
                            <p style="display:inline-block;">This Will Delete Customer Type <span style="font-weight:bold;">"@Model.Id-@Model.Name"</span> From You Database.</p>
                        </div>
                        <div class="col-sm-12">
                            <a class="btn btn-outline-danger pull-right btn-sm" asp-area="" asp-controller="CustomerType" asp-action="Index">Cancel</a>
                            <a asp-area="" asp-controller="CustomerType" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-primary pull-right btn-sm" style="margin-right:10px;">Remove</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

L01/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

L01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <p>Hello world !</p>
</div>

L01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - L01</title>

    <environment include="Development">
        <!--Font-Awesome-->
        <link rel="stylesheet" href="~/font-awesome/css/font-awesome.min.css" />
        <!-- Use Select 2 -->
        <link rel="stylesheet" href="~/dist/plugins/select2/select2.min.css" />
        <!-- Admin LTE Style -->
        <link rel="stylesheet" href="~/css/adminlte.css" />
        <!-- Use Google font -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700|Roboto&display=swap" rel="stylesheet">
        <!--Date Time Picker-->
        <link href="~/css/bootstrap-datepicker.css" rel="stylesheet" />
        <!-- Customize owner Style  -->
        <link rel="stylesheet" href="~/css/custom.css" />
    </environment>
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
            <!-- Left navbar links -->
            @RenderSection("Breadcrumb", required: false)
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link">@*<i class="fa fa-bars"></i>*@</a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-area="" asp-controller="Home" asp-action="Index" class="brand-link">
                <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                    style="opacity: .8">
                <span class="brand-text font-weight-light" text-align="center">L01</span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!--Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="nav-icon fa fa-home"></i>
                                <p> Dashboard</p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="fa fa-bar-chart"></i>
                                <p>General Operations<i class="right fa fa-angle-left"></i></p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="Customer" asp-action="Index" class="nav-link">
                                        <i class="fa fa-users" aria-hidden="true"></i>
                                        <p>Customer</p>
                                    </a>
                                </li>
                            </ul>
                        </li><!--nav-item has-treeview-->

                        <li class="nav-item has-treeview">
                            <a href="~/buttons.html" class="nav-link">
                                <i class="nav-icon fa fa-tasks"></i>
                                <p>
                                    Products
                                    <i class="right fa fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fa fa-circle-o nav-icon"></i>
                                        <p>Products</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="Customer" asp-action="Index" class="nav-link">
                                        <i class="fa fa-address-card-o nav-icon" aria-hidden="true"></i>
                                        <p>Category</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-cogs"></i>
                                <p>
                                    Settings
                                    <i class="right fa fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="CustomerType" asp-action="Index" class="nav-link">
                                        <i class="fa fa-circle-o nav-icon"></i>
                                        <p>Customer Type</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="LoanType" asp-action="LoanType" class="nav-link">
                                        <i class="fa fa-circle-o nav-icon"></i>
                                        <p>Loan Type</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="background-color:#fbfbfb;font-family: 'Roboto', sans-serif;font-size:13px;font-weight:normal;">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <script src="~/js/jquery.min.js"></script>
    <!-- InputMask -->
    <script src="~/dist/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/dist/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="~/dist/plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Select2 -->
    <script src="~/dist/plugins/select2/select2.full.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/adminlte.min.js"></script>
    <!--Date Time Packer -->
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/custom.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>